[위제현] 배민찬 1단계 - 회원가입, 로그인
sproutt/baeminchan pull request #3
Opened 2019-04-21 02:54 UTC by wijehyeon

* [x] SLF4J를 적용해 logging이 가능하도록 설정한다.
* [x] 로그인 사용자는 일반 사용자 권한과 관리자 권한을 가질 수 있는 구조로 설계한다.
* [x] 회원가입, 로그인과 같이 값을 서버에 전송해야 하는 기능은 AJAX로 구현한다.
* [x] 회원가입시 입력 데이터에 대한 유효성 체크는 서버 측에서 처리한다. 유효성 체크 요구사항은 배민찬 서비스 기준을 따른다.
* [x] 비밀번호는 BCrypt 알고리즘을 적용해 암호화한다.
spring security 라이브러리에서 제공하는 BCryptPasswordEncoder를 활용해 해결한다.

2019-04-21 10:25 UTC, dadadamarine reviewed
저번에 혁진멘토의 말에따라 답을 제시하기보단 생각 해볼수 있게 던지는 방향으로 리뷰를 달기위해 노력했습니다.
말투가 이상하게 보일거 같아서 먼저 변명 남깁니다

수고하셨습니다!

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/domain/LoginDTO.java
> +}
이거 acceptance Test 통과하나요?

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/domain/User.java
> +        return true;
저도 encode를 entity에서 실행하도록 코딩해둬서 생각을 해보았는데.
정책이 바뀌어 비밀번호 Encoder를 다른 객체로 바꿔야 하는 상황이 왔을때 비즈니스 로직뿐만 아니라 엔티티를 변경해야 하는 상황이 생기더라구요. 해서 Encoder객체와 관련된 부분은 모두 서비스로 빼주어야 맞는거 같은데 어떻게 생각하시나요

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/domain/UserRequestDTO.java
> +    @Email(message = "메일의 양식을 지켜주세요.")
@Column(unique = true) 속성은 JPA가 Database를 생성할때 유효한 속성이라고 합니다.
이 어노테이션을 Entity가 아닌 DTO에 적용했을때 어떤식으로 동작하나요?

참조 : https://stackoverflow.com/questions/30460596/jpa-column-unique-true-what-is-really-point-of-having-unique-attribute

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/domain/UserRequestDTO.java
> +        return new User(this);
다른 동료가가 비즈니스 로직에서 toUserEntity를 사용하고 같은 로직 안에서 DTO의 패스워드를 가져오는 코드를 작성했을때
DTO의 password가 인코딩 되어있을거라고 기대할까요?

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/config/WebConfig.java
> +    }
꼭 필요한 코드인가요?

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/service/UserService.java
> +    }
저는 생각못했던 예외네요. 훌륭하십니다.
이 비즈니스 로직을 따로 구현하지 않고 spring에서 자동으로 발생시켜주는 예외로 핸들링 하면 더 멋진 소스가 나올거 같습니다.

ps. 다시 생각해보면 비즈니스 로직에서 처리하는게 맞는것 같기도합니다.
spring 에서 발생시켜주는 에러는 모든 database관련 예외에 대해서 한종류의 exception만 반환하기때문에 구체적인 원인을 알기가 어려울 것 같습니다.

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/util/SessionUtil.java
> +                .orElseThrow(RuntimeException::new);
Optional.ofNullable을 사용한것과 사용하지 않았을때 어떤차이가 있나요?

2019-04-21 10:25 UTC, dadadamarine commented on src/main/java/codesquad/validate/ValidationExceptionControllerAdvice.java
> +        log.info("error message: {}", errorMessage);
msa.getMessage를 사용하신 이유가 무엇인가요?

2019-04-21 10:25 UTC, dadadamarine commented on src/test/java/codesquad/web/ApiUserAcceptanceTest.java
> +
HomeController에 대한 acceptanceTest도 진행해보시길 바랍니다.

2019-05-01 09:30 UTC, hyukjin-lee requested changes

2019-05-01 09:30 UTC, hyukjin-lee commented on baeminchan.iml
> +    <orderEntry type="library" name="Maven: org.springframework:spring-expression:5.0.7.RELEASE" level="project" />
이것도 처리바람

2019-05-01 09:30 UTC, hyukjin-lee commented on pom.xml
> +        </dependency>
indent 가 안맞네요

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/User.java
> +    public boolean match(LoginDTO loginDTO) {
뭘 매치한다는건지

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/UserRequestDTO.java
> +    private String phoneNumber;
쿠팡의 휴대폰번호 regex 정책에 맞게 해보세요

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/UserRequestDTO.java
> +    private String password2;
message source 를 만들었으면 활용해서 해보세요. 왜 만든건지;

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/service/UserService.java
> +            throw new BadRequestException("이미 존재하는 이메일입니다");
모든 에러처리는 AOP로 ControllerAdvice를 구현하여 처리하세요

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/service/UserService.java
> +    @Transactional(readOnly = true)
여기에 트랜젝셔널이 필요한 이유는?

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/UserRequestDTO.java
> +public class UserRequestDTO {
이름이 용도에 맞게 지어졌으면 좋겠음

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/UserResponseDTO.java
> +    }
Response를 DTO로 감싼 이유는?

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/service/UserService.java
> +        return userRepository.save(user.encode(passwordEncoder));
user.encodePassword

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/validate/ValidationExceptionControllerAdvice.java
> +    }
이 코드가 어떤 원리로 어떻게 동작하는지 쭉 설명해보세요

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/web/ApiUserController.java
> +    @ResponseStatus(HttpStatus.OK)
엔티티에 OK를 애초에 담아서 보내주는데  responseStatus 의 역할은 뭔가요

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/web/ApiUserController.java
> +    @ResponseStatus(HttpStatus.OK)
성공하면 created 를 responseEntity에 담아서 보내주는데 ok 를 왜 보내는지;

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/web/ApiUserController.java
> +        headers.setLocation(URI.create("/users/" + user.getId()));
generate url 함수를 만들어서 활용해보세요

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/web/HomeController.java
> +        return "/login";
중괄호 붙이는걸 컨벤션으로 합시다

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/web/HomeController.java
> +        return "/login";
이런 static 페이지들에 대한 정의는 config를 통해 정의해봅시다

2019-05-01 09:30 UTC, hyukjin-lee commented on src/main/java/codesquad/web/HomeController.java
> +        return "/login";
근데 로그인 한 사용자가 회원가입 버튼을 누른다고 홈페이지로 리다이렉트 되는게 일반적인 서비스 인가요?

2019-05-11 05:03 UTC, wijehyeon commented on src/main/java/codesquad/validate/ValidationExceptionControllerAdvice.java
> +    }
ValidationExceptionControllerAdvice에서 ExceptionHandler가 MethodArgumentNotValidException에 대한 예외를 캐치하면 구현된 로직대로 진행됨
-> List형의 errors를 만들어서 발생한 모든 에러들을 수집 -> 모든 errors의 각 error들을 ValidationErrorsResponse타입으로 묶어서 return 하고자함 -> ValidationErrorResponse에는 List<ValidationError>가 선언되어있음, ValidationError를 생성하기 위해서는 fieldName, errorMessage가 필요함 -> errorMessage를 뽑아오기 위해 아까 각자 for문으로 진행중이던 error(objectError)에서 get
Codes로 메세지가 담겨있는지 아닌지를 판단 -> 비어있으면 Optional.empty를 발생, 메세지가 있으면 존재함을 알리기 위해 codes[0]을 보냄 -> messages.properties에 있는 내용을 참조하여 errorMessage로 남김

2019-05-11 05:35 UTC, dadadamarine commented on src/main/java/codesquad/domain/JoinDTO.java
> +
messages.properties 이용해주세요. 
이렇게 메세지가 분리되어있으면 Validation 에러가 났을때 Message에 맞는 validation을 확인하려면 각 DTO를 다 확인해야합니다.

2019-05-11 05:35 UTC, dadadamarine commented on src/main/java/codesquad/validate/ValidationExceptionControllerAdvice.java
> +public class ValidationExceptionControllerAdvice {
Message를 Bean으로 등록해주세요. 안그러면 안돌아갑니다.

2019-05-11 13:30 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/JoinDTO.java
> +    @Pattern(regexp = "^[0-9a-zA-Z]+")
regex 중복제거하세요

2019-05-11 13:30 UTC, merged