[종근] 배민찬 1단계 - 회원가입, 로그인 구현
sproutt/baeminchan pull request #7
Opened 2019-07-18 12:02 UTC by Bellroute

2019-07-22 02:11 UTC, hyukjin-lee requested changes
구현하느라 고생하셨습니다
모든 댓글에 본인의 생각을 답글로 남겨주세요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/Account.java
> +    public static final int ADMIN = 1;
Enum type 으로 빼는게 좋지 않을까요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/Account.java
> +    @Pattern(regexp = "^\\d{3}-\\d{3,4}-\\d{4}$", message = "비밀번호 형식이 올바르지 않습니다.")
messageSourceAccesor를 적용해서 메시지를 설정파일로 관리해보세요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/Account.java
> +@Setter
setter는 어느경우에 필요한가요?

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/dto/SignUpDTO.java
> +    @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,16}$", message = "비밀번호 형식이 올바르지 않습니다.")
비밀번호를 사용하는 객체가 많아지면 개발하는 사람마다 서로 다른 정책을 적용할 수 있으니
중복을 줄일 필요성이 있어보입니다. 어떻게 하면 될까요?

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/dto/SignUpDTO.java
> +    @Column(nullable = false, name = "name")
DTO 는 엔티티가 아닌데 Column 을 붙여주신 이유가 뭔가요?

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/dto/SignUpDTO.java
> +    @Pattern(regexp = "^\\d{3}-\\d{3,4}-\\d{4}$", message = "전화번호 형식이 올바르지 않습니다.")
DTO에도 철저하게 validation 을 넣어주셨네요.
DTO에도 검증 절차를 넣으면 어떤 이점이 있고 어떤 단점이 있을까요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/exception/UnAuthenticationException.java
> +}
controller advice 를 적용해보세요 라고 했었습니다

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/exception/UnAuthenticationException.java
> +}
aop 에 대한 기본 개념을 잡고 controller advice 를 적용해보세요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/service/AccountService.java
> +    private static final String SESSIONED_USER = "sessionedUser";
세션이라 글로벌하게 쓰일 것 같은데 서비스에 두는게 최선일까요?

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/service/AccountService.java
> +    private PasswordEncoder passwordEncoder;
앞으로 스터디에서 Autowired 를 사용하지 말아봅시다

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/service/AccountService.java
> +        return new ResponseEntity<>(headers, HttpStatus.CREATED);
service 레이어는 Http 에 의존성을 갖지 않는게 낫지 않을까요?
(service 레이어가 Http를 모르게 설계하는게 낫지 않을까요?)
이것에 대해 곰곰히 생각해보고 답글 주세요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/service/AccountService.java
> +        if (!passwordEncoder.matches(loginDTO.getPassword(), account.getPassword())) {
둘다 인코딩 된 패스워드인데 passwordEncoder 로 매치 시키는 이유가 있나요? 궁금해서

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/java/codesquad/web/ApiAccountController.java
> +    @PostMapping("/member/sign-up")
- 는 안쓰는게 좋습니다

2019-07-22 02:11 UTC, hyukjin-lee commented on src/main/resources/static/js/script.js
> +    window.location = 'http://localhost:8080/login';
이렇게 하는게 맞을까요? 뭐가 문젠지 말하고 한번 고쳐보세요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/test/java/codesquad/config/PasswordEncoderTest.java
> +    }
이 테스트가 왜 필요 없는지 설명해보세요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/test/java/codesquad/domain/AccountTest.java
> +        Account account = new Account("be@gmail.com", password, "bell", "010-0000-0000");
빌더패턴을 적용해서 가독성있게 구현해보세요

2019-07-22 02:11 UTC, hyukjin-lee commented on src/test/java/codesquad/domain/AccountTest.java
> +        assertThat(account.matchPassword("11111111")).isFalse();
이런 경우 assertAll 을 한번 사용해봅시다

2019-07-22 02:11 UTC, hyukjin-lee commented on src/test/java/codesquad/service/AccountServiceTest.java
> +@SpringBootTest
Springboottest 를 붙인 이유가 뭘까요?

2019-07-22 08:29 UTC, Bellroute commented on src/main/java/codesquad/domain/Account.java
> +    public static final int ADMIN = 1;
Enum이 아직 생소해서 생각을 못했네요. 공부해서 반영해보겠습니다

2019-07-22 08:31 UTC, Bellroute commented on src/main/java/codesquad/domain/Account.java
> +    @Pattern(regexp = "^\\d{3}-\\d{3,4}-\\d{4}$", message = "비밀번호 형식이 올바르지 않습니다.")
학습 후 반영하겠습니다

2019-07-22 08:33 UTC, Bellroute commented on src/main/java/codesquad/domain/Account.java
> +@Setter
혹시 테스트코드에서 사용 되지 않을까 싶어서 추가 했었을텐데 그냥 습관처럼 추가 했던거 같습니다.

2019-07-22 08:39 UTC, Bellroute commented on src/main/java/codesquad/dto/SignUpDTO.java
> +    @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,16}$", message = "비밀번호 형식이 올바르지 않습니다.")
유틸클래스를 하나 만들어 regex를 상수화시켜 관리하는 방법은 어떤가요?

2019-07-22 08:40 UTC, Bellroute commented on src/main/java/codesquad/dto/SignUpDTO.java
> +    @Column(nullable = false, name = "name")
모델의 validation을 DTO에도 반영하는 과정에서 실수한 것 같습니다. 반영하겠습니다

2019-07-22 09:01 UTC, Bellroute commented on src/main/java/codesquad/dto/SignUpDTO.java
> +    @Pattern(regexp = "^\\d{3}-\\d{3,4}-\\d{4}$", message = "전화번호 형식이 올바르지 않습니다.")
DTO에 검증 절차 안넣으면 그냥 에러가 안걸리던데 문제있는 건가요?

2019-07-22 09:01 UTC, Bellroute commented on src/main/java/codesquad/exception/UnAuthenticationException.java
> +}
aop 공부하고 controller advice 반영하겠습니다

2019-07-22 09:03 UTC, Bellroute commented on src/main/java/codesquad/service/AccountService.java
> +    private PasswordEncoder passwordEncoder;
Autowired를 왜 쓰면 안되는지 궁금합니다

2019-07-22 09:14 UTC, Bellroute commented on src/main/java/codesquad/service/AccountService.java
> +        if (!passwordEncoder.matches(loginDTO.getPassword(), account.getPassword())) {
loginDTO에는 사용자가 로그인시 입력한 값이어서 인코딩 전 패스워드라 매치했습니다.

2019-07-22 09:14 UTC, Bellroute commented on src/main/java/codesquad/web/ApiAccountController.java
> +    @PostMapping("/member/sign-up")
넵

2019-07-22 09:17 UTC, Bellroute commented on src/main/resources/static/js/script.js
> +    window.location = 'http://localhost:8080/login';
정적(?)으로 구현해서 ul이 바뀌면 문제가 생길 것 같습니다. response에 리다이렉트 url을 함께 담아서 보내줘야 할까요?

2019-07-22 09:20 UTC, Bellroute commented on src/test/java/codesquad/config/PasswordEncoderTest.java
> +    }
이미 잘 구현된 라이브러리라서?
사실 passwordEncoder가 어떻게 돌아가는지 보려고 테스트 짠거였습니다.

2019-07-22 09:20 UTC, Bellroute commented on src/test/java/codesquad/domain/AccountTest.java
> +        Account account = new Account("be@gmail.com", password, "bell", "010-0000-0000");
빌더패턴 공부하고 반영하겠습니다.

2019-07-22 09:20 UTC, Bellroute commented on src/test/java/codesquad/domain/AccountTest.java
> +        assertThat(account.matchPassword("11111111")).isFalse();
assertAll 알아보고 반영하겠습니다.

2019-07-22 09:22 UTC, Bellroute commented on src/test/java/codesquad/service/AccountServiceTest.java
> +@SpringBootTest
passwordEncoder 반영시 이것저것 해보다가 안지웠던 것 같습니다

2019-07-26 03:35 UTC, hyukjin-lee commented on src/main/java/codesquad/dto/SignUpDTO.java
> +    @Pattern(regexp = "^\\d{3}-\\d{3,4}-\\d{4}$", message = "전화번호 형식이 올바르지 않습니다.")
여기에 적어준 이유를 알고 쓴건지 궁금해서 여쭤봤습니다.
혹시 이게 어떻게 동작하는지 아시나요?
hibernate의 bean validation은 
@Validated, @Valid, validator.validate() 를 호출 할 때 유효성 검사를 하는건데

@Entity 를 붙인 클래스를 유효성 검사하는건 이 코드에 없는 것 같은데
왜 붙이는 것 일까요? 

의문이 생겨서 찾아보니 JPA, Hibernate ORM을 사용하는 경우에는 엔티티를 영속화하거나 업데이트 할 때 validate를 내부적으로 한번 돌린다고 합니다. 
![image](https://user-images.githubusercontent.com/14870706/61924116-632d0100-afa1-11e9-8761-ce9b6fd368c3.png)

그러면 결론적으로 이 코드는 DTO에서 한번 @Valid를 통해 validate를 하고, Entity에서도 저장할 때 validate을 한번 더 하는 것인데, 왜 이렇게 두번이나 하게 구현해야하는 것 일까요?

2019-08-22 16:17 UTC, hyukjin-lee approved these changes
리뷰들 달고 확인버튼 누르는걸 깜빡해서 pending 걸려있었네요;

2019-08-22 16:17 UTC, hyukjin-lee commented on src/main/java/codesquad/service/AccountService.java
> +    private PasswordEncoder passwordEncoder;
https://www.youtube.com/watch?v=qmI7uJapocw

저번에 창환이가 꼭 보라고 올려준 것인데 참고 ~

2019-08-22 16:17 UTC, hyukjin-lee commented on src/main/resources/static/js/script.js
> +    window.location = 'http://localhost:8080/login';
localhost:8080은 현재 로컬에서만 이 서비스를 사용하겠다는 뜻인데..
https://4rgos.tistory.com/17
참고해서 상대경로로 잘 구현해보세요

2019-08-22 16:17 UTC, hyukjin-lee commented on src/test/java/codesquad/domain/AccountTest.java
> +        assertThat(account.matchPassword("11111111")).isFalse();
ㅋㅋㅋㅋ 군대냐;;

2019-09-21 14:48 UTC, closed without merging